package by.bsuir.akkerman.mobile.server.entity;
// Generated 07.12.2015 0:24:44 by Hibernate Tools 4.3.1


import by.bsuir.akkerman.mobile.server.dao.EntityHelper;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * GroupTariff generated by hbm2java
 */
public class GroupTariff extends EntityHelper implements java.io.Serializable {


     private Integer id;
     private String groupName;
     private Set<TariffPlan> tariffPlans = new HashSet<TariffPlan>(0);

    public GroupTariff() {
    }

	
    public GroupTariff(String groupName) {
        this.groupName = groupName;
    }
    public GroupTariff(String groupName, Set<TariffPlan> tariffPlans) {
       this.groupName = groupName;
       this.tariffPlans = tariffPlans;
    }
   
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Set<TariffPlan> getTariffPlans() {
        return this.tariffPlans;
    }
    
    public void setTariffPlans(Set<TariffPlan> tariffPlans) {
        this.tariffPlans = tariffPlans;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public Collection getChild() {
        return null;
    }

    @Override
    public Collection getParent() {
        return getTariffPlans();
    }

}


