package by.bsuir.akkerman.mobile.server.entity;
// Generated 07.12.2015 0:24:44 by Hibernate Tools 4.3.1


import by.bsuir.akkerman.mobile.server.dao.EntityHelper;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MmsInfo generated by hbm2java
 */
public class MmsInfo extends EntityHelper implements java.io.Serializable {


     private Integer id;
     private Subscriber subscriberByToSubscriberId;
     private Subscriber subscriberByFromSubscriberId;
     private Date mmsDate;
     private Date mmsTime;
     private String status;
     private Set<Subscriber> child = new HashSet<>(0); 

    public MmsInfo() {
    }

    public MmsInfo(Subscriber subscriberByToSubscriberId, Subscriber subscriberByFromSubscriberId, Date mmsDate, Date mmsTime, String status) {
       this.subscriberByToSubscriberId = subscriberByToSubscriberId;
       this.subscriberByFromSubscriberId = subscriberByFromSubscriberId;
       this.mmsDate = mmsDate;
       this.mmsTime = mmsTime;
       this.status = status;
    }

    
    public void setId(Integer id) {
        this.id = id;
    }
    public Subscriber getSubscriberByToSubscriberId() {
        return this.subscriberByToSubscriberId;
    }
    
    public void setSubscriberByToSubscriberId(Subscriber subscriberByToSubscriberId) {
        this.subscriberByToSubscriberId = subscriberByToSubscriberId;
    }
    public Subscriber getSubscriberByFromSubscriberId() {
        return this.subscriberByFromSubscriberId;
    }
    
    public void setSubscriberByFromSubscriberId(Subscriber subscriberByFromSubscriberId) {
        this.subscriberByFromSubscriberId = subscriberByFromSubscriberId;
    }
    public Date getMmsDate() {
        return this.mmsDate;
    }
    
    public void setMmsDate(Date mmsDate) {
        this.mmsDate = mmsDate;
    }
    public Date getMmsTime() {
        return this.mmsTime;
    }
    
    public void setMmsTime(Date mmsTime) {
        this.mmsTime = mmsTime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public Collection getChild() {
        child.add(getSubscriberByFromSubscriberId());
        child.add(getSubscriberByToSubscriberId());
        return child;
    }

    @Override
    public Collection getParent() {
        return null;
    }




}


