package by.bsuir.akkerman.mobile.server.entity;
// Generated 07.12.2015 0:24:44 by Hibernate Tools 4.3.1


import by.bsuir.akkerman.mobile.server.dao.EntityHelper;
import java.util.HashSet;
import java.util.Set;

/**
 * Subscriber generated by hbm2java
 */
public class Subscriber extends EntityHelper implements java.io.Serializable {


     private Integer id;
     private CallForwarding callForwarding;
     private Contract contract;
     private TariffPlan tariffPlan;
     private String roaming;
     private Set<SmsInfo> smsInfosForToSubscriberId = new HashSet<SmsInfo>(0);
     private Set<InternetInfo> internetInfos = new HashSet<InternetInfo>(0);
     private Set<MmsInfo> mmsInfosForToSubscriberId = new HashSet<MmsInfo>(0);
     private Set<VoiceMessage> voiceMessagesForToSubscriberId = new HashSet<VoiceMessage>(0);
     private Set<MmsInfo> mmsInfosForFromSubscriberId = new HashSet<MmsInfo>(0);
     private Set<VoiceMessage> voiceMessagesForFromSubscriberId = new HashSet<VoiceMessage>(0);
     private Set<CallInfo> callInfosForFromSubscriberId = new HashSet<CallInfo>(0);
     private Set<CallInfo> callInfosForToSubscriberId = new HashSet<CallInfo>(0);
     private Set<SmsInfo> smsInfosForFromSubscriberId = new HashSet<SmsInfo>(0);
     private Set<EntityHelper> child = new HashSet<>(0); 

    public Subscriber() {
    }

	
    public Subscriber(CallForwarding callForwarding, Contract contract, TariffPlan tariffPlan) {
        this.callForwarding = callForwarding;
        this.contract = contract;
        this.tariffPlan = tariffPlan;
    }
    public Subscriber(CallForwarding callForwarding, Contract contract, TariffPlan tariffPlan, String roaming, Set<SmsInfo> smsInfosForToSubscriberId, Set<InternetInfo> internetInfos, Set<MmsInfo> mmsInfosForToSubscriberId, Set<VoiceMessage> voiceMessagesForToSubscriberId, Set<MmsInfo> mmsInfosForFromSubscriberId, Set<VoiceMessage> voiceMessagesForFromSubscriberId, Set<CallInfo> callInfosForFromSubscriberId, Set<CallInfo> callInfosForToSubscriberId, Set<SmsInfo> smsInfosForFromSubscriberId) {
       this.callForwarding = callForwarding;
       this.contract = contract;
       this.tariffPlan = tariffPlan;
       this.roaming = roaming;
       this.smsInfosForToSubscriberId = smsInfosForToSubscriberId;
       this.internetInfos = internetInfos;
       this.mmsInfosForToSubscriberId = mmsInfosForToSubscriberId;
       this.voiceMessagesForToSubscriberId = voiceMessagesForToSubscriberId;
       this.mmsInfosForFromSubscriberId = mmsInfosForFromSubscriberId;
       this.voiceMessagesForFromSubscriberId = voiceMessagesForFromSubscriberId;
       this.callInfosForFromSubscriberId = callInfosForFromSubscriberId;
       this.callInfosForToSubscriberId = callInfosForToSubscriberId;
       this.smsInfosForFromSubscriberId = smsInfosForFromSubscriberId;
    }
   
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CallForwarding getCallForwarding() {
        return this.callForwarding;
    }
    
    public void setCallForwarding(CallForwarding callForwarding) {
        this.callForwarding = callForwarding;
    }
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }
    public TariffPlan getTariffPlan() {
        return this.tariffPlan;
    }
    
    public void setTariffPlan(TariffPlan tariffPlan) {
        this.tariffPlan = tariffPlan;
    }
    public String getRoaming() {
        return this.roaming;
    }
    
    public void setRoaming(String roaming) {
        this.roaming = roaming;
    }
    public Set<SmsInfo> getSmsInfosForToSubscriberId() {
        return this.smsInfosForToSubscriberId;
    }
    
    public void setSmsInfosForToSubscriberId(Set<SmsInfo> smsInfosForToSubscriberId) {
        this.smsInfosForToSubscriberId = smsInfosForToSubscriberId;
    }
    public Set<InternetInfo> getInternetInfos() {
        return this.internetInfos;
    }
    
    public void setInternetInfos(Set<InternetInfo> internetInfos) {
        this.internetInfos = internetInfos;
    }
    public Set<MmsInfo> getMmsInfosForToSubscriberId() {
        return this.mmsInfosForToSubscriberId;
    }
    
    public void setMmsInfosForToSubscriberId(Set<MmsInfo> mmsInfosForToSubscriberId) {
        this.mmsInfosForToSubscriberId = mmsInfosForToSubscriberId;
    }
    public Set<VoiceMessage> getVoiceMessagesForToSubscriberId() {
        return this.voiceMessagesForToSubscriberId;
    }
    
    public void setVoiceMessagesForToSubscriberId(Set<VoiceMessage> voiceMessagesForToSubscriberId) {
        this.voiceMessagesForToSubscriberId = voiceMessagesForToSubscriberId;
    }
    public Set<MmsInfo> getMmsInfosForFromSubscriberId() {
        return this.mmsInfosForFromSubscriberId;
    }
    
    public void setMmsInfosForFromSubscriberId(Set<MmsInfo> mmsInfosForFromSubscriberId) {
        this.mmsInfosForFromSubscriberId = mmsInfosForFromSubscriberId;
    }
    public Set<VoiceMessage> getVoiceMessagesForFromSubscriberId() {
        return this.voiceMessagesForFromSubscriberId;
    }
    
    public void setVoiceMessagesForFromSubscriberId(Set<VoiceMessage> voiceMessagesForFromSubscriberId) {
        this.voiceMessagesForFromSubscriberId = voiceMessagesForFromSubscriberId;
    }
    public Set<CallInfo> getCallInfosForFromSubscriberId() {
        return this.callInfosForFromSubscriberId;
    }
    
    public void setCallInfosForFromSubscriberId(Set<CallInfo> callInfosForFromSubscriberId) {
        this.callInfosForFromSubscriberId = callInfosForFromSubscriberId;
    }
    public Set<CallInfo> getCallInfosForToSubscriberId() {
        return this.callInfosForToSubscriberId;
    }
    
    public void setCallInfosForToSubscriberId(Set<CallInfo> callInfosForToSubscriberId) {
        this.callInfosForToSubscriberId = callInfosForToSubscriberId;
    }
    public Set<SmsInfo> getSmsInfosForFromSubscriberId() {
        return this.smsInfosForFromSubscriberId;
    }
    
    public void setSmsInfosForFromSubscriberId(Set<SmsInfo> smsInfosForFromSubscriberId) {
        this.smsInfosForFromSubscriberId = smsInfosForFromSubscriberId;
    }

    @Override
    public Set<EntityHelper> getChild() {
        child.add(this.getTariffPlan());
        child.add(this.getCallForwarding());
        child.add(this.getContract());
        return child;
    }

    @Override
    public Set<EntityHelper> getParent() {
        Set<EntityHelper> parents = new HashSet<>();
        parents.add((EntityHelper) getCallInfosForFromSubscriberId());
        parents.add((EntityHelper) getCallInfosForToSubscriberId());
        parents.add((EntityHelper) getSmsInfosForFromSubscriberId());
        parents.add((EntityHelper) getSmsInfosForToSubscriberId());
        parents.add((EntityHelper) getMmsInfosForFromSubscriberId());
        parents.add((EntityHelper) getMmsInfosForToSubscriberId());
        parents.add((EntityHelper) getVoiceMessagesForFromSubscriberId());
        parents.add((EntityHelper) getVoiceMessagesForToSubscriberId());
        parents.add((EntityHelper) getInternetInfos());
        return parents;        
    }

    @Override
    public int getId() {
        return this.id;
    }

}


