package by.bsuir.akkerman.mobile.server.entity;
// Generated 07.12.2015 0:24:44 by Hibernate Tools 4.3.1


import by.bsuir.akkerman.mobile.server.dao.EntityHelper;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * TypePerson generated by hbm2java
 */
public class TypePerson extends EntityHelper implements java.io.Serializable {


     private Integer id;
     private String typeName;
     private Set<Contract> contracts = new HashSet<Contract>(0);

    public TypePerson() {
    }

	
    public TypePerson(String typeName) {
        this.typeName = typeName;
    }
    public TypePerson(String typeName, Set<Contract> contracts) {
       this.typeName = typeName;
       this.contracts = contracts;
    }
   
    @Override
    public int getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set<Contract> getContracts() {
        return this.contracts;
    }
    
    public void setContracts(Set<Contract> contracts) {
        this.contracts = contracts;
    }


    @Override
    public Collection getChild() {
        return null;
    }

    @Override
    public Collection getParent() {
        return getContracts();
    }




}


